import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { RegistryBrowser } from "@/components/registry-browser";
import { entries } from "@/lib/data";
export default function Home() {
  return <div className="shell"><SiteNav />
    <main>
      <section className="hero"><div><div className="eyebrow"><span className="live-dot" /> An open-source agent content firewall</div><h1>Read the web.<br /><em>Keep your intent.</em></h1><p className="lead">Web pages, tool results, screenshots. Inspect untrusted content before it becomes your agent’s next instruction.</p><div className="hero-actions"><Link className="button" href="/developers">Protect your agent <span>↗</span></Link><Link className="text-link" href="/scan">Explore the scan lab →</Link></div><div className="hero-meta">Apache-2.0 <span>·</span> TypeScript SDK <span>·</span> Local policy, optional Jev</div></div>
        <div className="flow-card"><div className="panel-heading"><span>THE TRUST BOUNDARY</span><span>01 — 03</span></div><div className="flow-row"><b>01</b><div><strong>Untrusted input</strong><p>Text · HTML · images · screenshots</p></div><span>↓</span></div><div className="flow-row"><b>02</b><div><strong>Inspect the evidence</strong><p>Static signals + atomic semantic questions</p></div><span>↓</span></div><div className="flow-row"><b>03</b><div><strong>Your code decides</strong><p>Allow · sanitize · review · block</p></div><span>↗</span></div><div className="flow-foot">The registry is optional. Your protection is local.</div></div>
      </section>
      <div className="workspace"><aside className="sidebar"><div className="eyebrow">Explore</div><a className="side-link selected" href="#registry">▦ &nbsp; Evidence registry <span>{entries.length}</span></a><Link className="side-link" href="/scan">⌕ &nbsp; Scan lab</Link><Link className="side-link" href="/developers">⌘ &nbsp; Agent integrations</Link><div className="eyebrow side-heading">Inspection surfaces</div><div className="surface">Text & DOM <span>Available</span></div><div className="surface">Images & screenshots <span>Experimental</span></div><div className="surface">PDF extraction <span>Bring your parser</span></div><div className="aside-note"><span className="eyebrow">Built in the open</span><h3>Evidence, not accusations.</h3><p>A finding describes content. It does not establish who placed it or whether a site was compromised.</p><a className="text-link" href="https://github.com/cyberesia/jev-traps/blob/main/CONTRIBUTING.md">Contribute a fixture ↗</a></div></aside>
        <section id="registry" className="registry-main"><div className="section-heading"><div className="eyebrow">The evidence library</div><h2>Patterns worth recognizing.</h2><p>Localized observations. Explicit status. Redacted evidence.</p></div><div className="demo-banner"><strong>Demo collection</strong><span>These {entries.length} synthetic examples explain the format. They are not reports about real websites.</span></div><RegistryBrowser entries={entries} /></section>
        <aside className="right-rail"><div className="rail-card pink"><span className="eyebrow">New inspection surface</span><div className="frame-art" aria-hidden="true"><span>UNTRUSTED FRAME</span><i /><b>↖ visual region</b></div><h3>The trap can be in the pixels.</h3><p>Inspect screenshots and image attachments with a vision adapter, then classify localized observations with Jev.</p><Link className="text-link" href="/developers#vision">Explore image inspection ↗</Link></div><div className="rail-card"><span className="eyebrow">Bring your agent</span><h3>One boundary.<br />Any agent stack.</h3><div className="provider-list"><span>Anthropic <small>Claude agents</small></span><span>OpenAI <small>Tool-using agents</small></span><span>Open weights <small>Your inference server</small></span></div><Link className="text-link" href="/developers">See calls & data flow →</Link></div></aside>
      </div>
    </main><footer className="footer"><span><strong>Jev Traps</strong> / by cyberesia</span><span>Experimental security tooling · Apache-2.0</span><a href="https://github.com/cyberesia/jev-traps">Source & documentation ↗</a></footer>
  </div>;
}
