import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { RegistryBrowser } from "@/components/registry-browser";
import { AutomatedObservations } from "@/components/automated-observations";
import { JevDecisionLab } from "@/components/jev-decision-lab";
import { JevEcosystem } from "@/components/jev-ecosystem";
import { entries } from "@/lib/data";
export default function Home() {
 return <div className="shell"><SiteNav/><main>
  <section className="hero jev-hero"><div><div className="eyebrow"><span className="live-dot"/> Built around TypeSafe Jev</div><h1>Read the content.<br/><em>Recognize the intent.</em></h1><p className="lead">Jev turns ambiguous content into explicit judgments. Jev Traps turns those judgments into a boundary your agent can enforce.</p><div className="hero-actions"><a className="button" href="#decision-lab">Watch a decision unfold <span>↓</span></a><Link className="text-link" href="/developers">Integrate the SDK ↗</Link></div><div className="hero-meta">Open source <span>·</span> Typed decisions <span>·</span> Host-enforced policy</div><div className="hero-principle"><span>JEV</span><p>Classifies meaning</p><i>→</i><span>CODE</span><p>Controls actions</p></div></div><AutomatedObservations/></section>
  <div className="principle-strip"><div><b>06 + 01</b><span>Atomic judgments + content role</span></div><div><b>04</b><span>Explicit policy outcomes</span></div><div><b>01</b><span>Human review before confirmation</span></div><a href="/how-it-works">Why a decision model? <span>↗</span></a></div>
  <JevDecisionLab/>
  <section className="use-map"><div className="section-top"><div><div className="eyebrow">Where Jev intervenes</div><h2>From the first read<br/><span>to the review queue.</span></h2></div><Link className="text-link" href="/how-it-works#registry">Follow the complete path ↗</Link></div><div className="use-map-grid"><Link href="/how-it-works#policy"><span>01 / CONTENT</span><h3>Threat classification</h3><p>Agent instruction, secret request, tool manipulation or benign quotation?</p><b>Jev judges intent ↗</b></Link><Link href="/how-it-works#policy"><span>02 / ENFORCEMENT</span><h3>Risk & routing</h3><p>Structured findings become a score and one of four host-enforced outcomes.</p><b>Deterministic policy ↗</b></Link><Link href="/how-it-works#registry"><span>03 / PRIVATE INBOX</span><h3>Report triage</h3><p>Optional Jev screening helps operators prioritize a report without granting publication.</p><b>Jev assists review ↗</b></Link></div></section>
  <div className="workspace"><aside className="sidebar"><div className="eyebrow">Explore</div><a className="side-link selected" href="#registry">▦ Evidence registry <span>{entries.length}</span></a><Link className="side-link" href="/how-it-works">How Jev works ↗</Link><Link className="side-link" href="/preventive">Preventive inspection ↗</Link><a className="side-link" href="#agents">Agents & ecosystem ↓</a><div className="aside-note"><span className="eyebrow">Evidence first</span><h3>Content has provenance.</h3><p>A signal does not identify an attacker or establish that a website was compromised.</p></div></aside><section id="registry" className="registry-main"><div className="section-heading"><div className="eyebrow">The reviewed evidence library</div><h2>Patterns worth recognizing.</h2><p>Localized observations. Explicit status. Redacted evidence.</p></div><div className="demo-banner"><strong>Demo collection</strong><span>These {entries.length} synthetic examples explain the format. They are not reports about real websites.</span></div><RegistryBrowser entries={entries}/></section><aside className="right-rail"><div className="rail-card pink"><span className="eyebrow">Expand the boundary</span><div className="frame-art" aria-hidden="true"><span>UNTRUSTED FRAME</span><i/><b>↖ visual region</b></div><h3>The trap can be in the pixels.</h3><p>Your vision provider observes the frame. Jev classifies the extracted observations. Code withholds flagged images.</p><Link className="text-link" href="/developers#vision">Explore image inspection ↗</Link></div><div className="rail-card"><span className="eyebrow">Next inspection surface</span><h3>Watch the sources<br/>your agents use.</h3><p>A preventive program for documentation, retrieval sources and authorized attachments.</p><Link className="text-link" href="/preventive">Explore the worker design ↗</Link></div></aside></div>
  <JevEcosystem/>
 </main><footer className="footer"><span><strong>Jev Traps</strong> / by cyberesia</span><span>Powered by TypeSafe Jev · Apache-2.0</span><a href="https://github.com/cyberesia/jev-traps">Source & documentation ↗</a></footer></div>;
}
