'use client';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import type { PageScan } from '@/lib/url-scan';
const siteKey=process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY??'';
const outcomes={allow:'No policy threshold reached',sanitize:'Content needs sanitization',review:'This page needs a closer look',block:'Content should be withheld'};
export function UrlScan(){
 const [url,setUrl]=useState('');const [config,setConfig]=useState<{enabled:boolean;semantic:boolean;destinationSemantic:boolean}|null>(null);
 const [semantic,setSemantic]=useState(false);const [destinationSemantic,setDestinationSemantic]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<PageScan|null>(null);const [scannedURL,setScannedURL]=useState('');
 const challenge=useRef<HTMLDivElement>(null);const widget=useRef<string|null>(null);const token=useRef('');const requestRef=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/scan',{signal:c.signal,cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setConfig).catch(()=>{if(!c.signal.aborted)setConfig({enabled:false,semantic:false,destinationSemantic:false});});return()=>{c.abort();requestRef.current?.abort();};},[]);
 useEffect(()=>{if(!siteKey||!config?.enabled)return;const render=()=>{if(window.turnstile&&challenge.current&&widget.current===null)widget.current=window.turnstile.render(challenge.current,{sitekey:siteKey,callback:t=>{token.current=t;},'expired-callback':()=>{token.current='';}});};render();if(!window.turnstile){const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=render;document.head.appendChild(script);} },[config?.enabled]);
 async function scan(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setResult(null);setBusy(true);const controller=new AbortController();requestRef.current=controller;const timer=setTimeout(()=>controller.abort(),60000);
  try{const response=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim(),semantic,destinationSemantic,turnstileToken:token.current,website:new FormData(e.currentTarget).get('website')}),signal:controller.signal});const body=await response.json();if(!response.ok)throw Error(body.error??'Unable to complete the scan.');setResult(body);setScannedURL(url.trim());}
  catch(err){setError(controller.signal.aborted?'Scan stopped. No verdict was produced.':err instanceof Error?err.message:'Unable to complete the scan.');}
  finally{clearTimeout(timer);requestRef.current=null;setBusy(false);token.current='';if(widget.current!==null)window.turnstile?.reset(widget.current);}
 }
 return <><section className="url-inspector"><div className="scan-service"><span className="eyebrow">Public page inspection</span><span>{config===null?'Checking availability…':config.enabled?'Live inspection enabled':'Live scanning not configured'}</span></div><form onSubmit={scan}><label className="scan-url-label" htmlFor="page-url">Which page should we inspect?</label><div className="scan-url-row"><input id="page-url" type="url" inputMode="url" autoComplete="url" maxLength={2048} required placeholder="https://example.com/page" value={url} disabled={busy} onChange={e=>{setUrl(e.target.value);setResult(null);setError('');}}/><button className="button" disabled={!config?.enabled||busy}>{busy?'Inspecting…':'Inspect page ↗'}</button></div><p className="note">Public HTTPS pages only. Remove query parameters and fragments. Do not submit private or signed links.</p><div className="scan-options"><label><input type="checkbox" checked={semantic} disabled={!config?.semantic||busy} onChange={e=>{setSemantic(e.target.checked);setResult(null);}}/><span><strong>Add Jev content analysis</strong><small>{config?.semantic?'Send selected page excerpts to TypeSafe Jev for intent classification.':'Not available on this deployment. Static page inspection uses no model.'}</small></span><b>{semantic?'JEV + STATIC':'STATIC'}</b></label><label><input type="checkbox" checked={destinationSemantic} disabled={!config?.destinationSemantic||busy} onChange={e=>{setDestinationSemantic(e.target.checked);setResult(null);}}/><span><strong>Ask Jev about an unknown destination</strong><small>{config?.destinationSemantic?'After the local threat-feed check, send only the URL and hostname to Jev before retrieval.':'The local threat-feed preflight still runs when configured on the worker.'}</small></span><b>{destinationSemantic?'JEV URL':'LOCAL FEED'}</b></label></div><div hidden><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{config?.enabled&&siteKey&&<div ref={challenge}/>}<p className="scan-disclosure">The destination is checked before retrieval. {destinationSemantic?'The URL and hostname go to TypeSafe. ':''}Only if preflight permits it does the target website receive a request. {semantic?'Selected page excerpts then go to TypeSafe.':'No page content goes to a model.'} Results are not added to the registry.</p></form>
 {config&&!config.enabled&&<div className="scan-notice"><strong>This deployment has no live scanner yet.</strong><p>You can submit the page URL for human review. This does not perform an instant scan.</p><a href="/submit">Report a page URL →</a></div>}
 {busy&&<div className="scan-progress" role="status"><span className="scan-spinner"/><div><strong>Checking the destination before retrieval…</strong><p>{semantic?'If preflight permits retrieval, page signals and their intent will be inspected.':'If preflight permits retrieval, the initial response will receive static inspection.'} This can take up to a minute.</p></div><button onClick={()=>requestRef.current?.abort()}>Cancel</button></div>}
 {error&&<div className="scan-notice error" role="alert">{error}</div>}</section>
 {result?.kind==='destination'&&<section className="url-result result-block" aria-live="polite"><div className="scan-service"><span className="eyebrow">DESTINATION PREFLIGHT / RETRIEVAL STOPPED</span><span>{result.totalMs} ms · no page request</span></div><div className="scan-result-heading"><div><p className="scan-result-url">{scannedURL}</p><h2>{result.destination.matches.length?'This exact destination was reported before retrieval.':'Destination signals stopped automatic retrieval.'}</h2></div></div><p>{result.destination.reason}</p>{result.destination.matches.map((match,i)=><article className="panel" key={i}><span className="eyebrow">{match.source} · {match.scope.replace('_',' ')} · {match.freshness}</span><p>The feed marked this indicator {match.status}{match.threat?` (${match.threat})`:''} at {match.reportedAt}.</p></article>)}{result.destination.semantic&&<p className="note">URL-level Jev: {result.destination.semantic.returnedModel??result.destination.semantic.requestedModel}.</p>}<p className="note">No page was fetched and no content verdict was produced. Feed and model signals are time-bound evidence, not proof about a site owner.</p><a className="text-link" href="/submit">Send a separate report for review →</a></section>}
 {result?.kind==='content'&&<section className={`url-result result-${result.action}`} aria-live="polite"><div className="scan-service"><span className="eyebrow">{result.mode==='jev'?'JEV + STATIC':'STATIC ONLY'} / INSPECTION COMPLETE</span><span>{result.totalMs} ms · {(result.bytes/1024).toFixed(1)} KiB</span></div>{result.destination.action==='review'&&<div className="scan-notice"><strong>Destination intelligence needs review.</strong><p>{result.destination.reason}</p></div>}<div className="scan-result-heading"><div><p className="scan-result-url">{scannedURL}</p><h2>{outcomes[result.action]}</h2></div><div className="scan-result-score"><strong>{result.risk.toFixed(3)}</strong><span>policy risk score</span></div></div><p className="note">{result.action==='allow'?'This is not a safety certificate. Unchecked content and attacks may remain.':'This outcome applies to the inspected response, not to every page on the domain.'} Scores are heuristic, not calibrated probabilities.</p><div className="scan-metrics"><span><b>{result.findingCount}</b> findings</span><span><b>{result.fetchMs} ms</b> retrieval</span><span><b>{result.inspectionMs} ms</b> analysis</span><span><b>{result.calls}</b> content Jev calls</span></div><div className="scan-findings">{result.findings.length?result.findings.map((f,i)=><article key={i}><div><span className="eyebrow">{f.detector} · {f.severity}</span><h3>{f.type.replaceAll('_',' ')}</h3><p>{f.reason}</p></div><span>{f.confidence.toFixed(3)}</span></article>):<p>No findings were returned for the inspected content.</p>}</div><details><summary>Scope, model and provenance</summary><p>{result.coverage}</p><p>Destination preflight: {result.destination.intelligence} · {result.destination.reason}{result.destination.semantic?` · URL model: ${result.destination.semantic.returnedModel??result.destination.semantic.requestedModel}`:''}</p><p>Content model: {result.models.join(', ')||'No content model called'} · Detector: {result.detectorVersion}<br/>Inspected: {result.scannedAt} · Redirects: {result.redirects}</p><p>Raw HTML and payloads are withheld. The fetched page is never embedded or rendered here.</p></details><a className="text-link" href="/submit">Send a separate report for review →</a></section>}</>;
}
