import deployments from "@/data/deployments.json";
const projects = [
 {name:"jev-mcp",owner:"burnigtm",category:"Routing & verification",description:"Typed judgments for coding loops, tool routing and evidence checks. The host retains execution control.",url:"https://github.com/burnigtm/jev-mcp",mark:"↗"},
 {name:"pi-heed",owner:"Nyarlathoteppppp",category:"Runtime constraints",description:"Checks tool calls against the user’s constraints. Jev classifies intent; deterministic rules enforce the boundary.",url:"https://github.com/Nyarlathoteppppp/pi-heed",mark:"⊣"},
 {name:"tax-doc-classifier",owner:"kyotofin",category:"Classification & confidence",description:"Classifies document pages into explicit choices, then uses confidence gates to route uncertain cases.",url:"https://github.com/kyotofin/tax-doc-classifier",mark:"▤"},
];
export function JevEcosystem() {
  const agents = deployments as {name:string;url:string;description:string;verifiedAt:string}[];
  return <section className="ecosystem" id="agents"><div className="section-top"><div><div className="eyebrow">One principle, different applications</div><h2>Jev judges. <span>Code acts.</span></h2></div><p>Three independent projects that show why typed decisions matter. Ecosystem references, not claimed Jev Traps deployments.</p></div><div className="ecosystem-grid">{projects.map(p=><a className="ecosystem-card" href={p.url} key={p.name}><div className="ecosystem-symbol">{p.mark}</div><div className="eyebrow">{p.category}</div><h3>{p.name} <span>↗</span></h3><p>{p.description}</p><small>{p.owner} / source on GitHub</small></a>)}</div><div className="adoption-strip"><div><div className="eyebrow">Opt-in Jev Traps deployments</div><h3>{agents.length ? `${agents.length} documented deployment${agents.length===1?"":"s"}` : "Be the first documented integration."}</h3><p>No hidden tracking. Listings require a public integration reference and maintainer review.</p></div><a className="button" href="https://github.com/cyberesia/jev-traps/blob/main/docs/AGENT-DIRECTORY.md">List your agent ↗</a></div>{agents.length>0&&<div className="ecosystem-grid">{agents.map(a=><a className="ecosystem-card" key={a.url} href={a.url}><h3>{a.name}</h3><p>{a.description}</p><small>Reference checked {a.verifiedAt}</small></a>)}</div>}</section>;
}
