import { SiteNav } from "@/components/site-nav";
import { JevDecisionLab } from "@/components/jev-decision-lab";
import { DEFAULT_POLICY } from "@jev-traps/core";
import recordings from "@/data/jev-recordings.json";
export default function HowItWorks() {
 return <div className="shell"><SiteNav/><main><header className="dev-header"><div className="eyebrow">Why Jev / inspectable by design</div><h1>Meaning needs judgment.<br/><em>Actions need rules.</em></h1><p className="lead">A security article and an injection can contain the same words. Jev helps distinguish their intent through independent, typed questions.</p></header><JevDecisionLab/>
 <section id="policy" className="method-section"><div className="section-top"><div className="eyebrow">01 / classify, rate, enforce</div><h2>What produces the action?</h2></div><div className="method-grid"><article className="panel"><h3>Jev classifies intent</h3><p>Six Noul judgments measure agent direction, goal override, secrets, tools, navigation and benign quotation. A Choice answer describes the content’s role. The official TypeSafe SDK submits them together.</p><p>Confidence describes model certainty, not factual truth. A quotation can reduce semantic findings; it does not remove the need to examine context.</p></article><article className="panel"><h3>Host code computes risk</h3><p>Static and semantic findings contribute by confidence and severity. For text inspection, semantic signals additionally influence the final action. HTML aggregation follows its own report path.</p><pre className="code">{JSON.stringify(DEFAULT_POLICY,null,2)}</pre><p>These values come from the current core package. Secret requests, goal overrides and hidden content have additional policy rules; risk is not simply the average of the bars.</p><a className="text-link" href="https://github.com/cyberesia/jev-traps/blob/main/packages/core/src/policy.ts">Read the exact policy ↗</a></article></div></section>
 <section id="registry" className="method-section"><div className="section-top"><div><div className="eyebrow">02 / evidence has a journey</div><h2>Detection is not publication.</h2></div><p>Each boundary has an owner. Jev helps interpret meaning; it never grants publishing privileges.</p></div><ol className="journey"><li><b>01</b><div><h3>Inspect in the agent host</h3><p>Text/DOM goes through local signals and optional Jev classification. Image bytes go to an explicitly selected vision provider; its observations then go to Jev.</p><span>LOCAL CODE + OPTIONAL JEV</span></div></li><li><b>02</b><div><h3>Validate an incoming report</h3><p>Bounded input, URL validation, origin checks, Turnstile and quota checks filter visitor submissions. SDK observations use an ingestion credential. These checks are deterministic, not Jev judgments.</p><span>SERVER VALIDATION</span></div></li><li><b>03</b><div><h3>Let Jev assist private triage</h3><p>An operator can select a pending report for optional semantic triage: relevance, sensitive content, reviewer-directed instructions and benign quotation. Only that note is sent to TypeSafe; no URL is fetched.</p><span>OPTIONAL JEV · OPERATOR-TRIGGERED</span></div></li><li><b>04</b><div><h3>Reproduce, redact, review</h3><p>The report remains pending. A human verifies the evidence and submits the public record through a reviewed PR. No Jev score automatically confirms a trap.</p><span>HUMAN REVIEW + GIT</span></div></li></ol>
 <div className="panel"><h3>Private triage, with typed output</h3><pre className="code">pnpm triage:submission &lt;pending-submission-uuid&gt;</pre><p className="note">Requires the private triage migration, DATABASE_URL and TYPESAFE_API_KEY. Failure leaves the report pending. It neither accepts nor rejects a submission.</p>{(recordings.triage as {id:string;route:string;returnedModel:string|null;durationMs:number}[]).map(row=><div className="kv" key={row.id}><span>{row.id}</span><span>{row.route.replaceAll("_"," ")} · {row.durationMs} ms · {row.returnedModel}</span></div>)}<p className="note">Any examples above are recorded synthetic triage cases, never private submissions.</p></div></section>
 <section className="method-section"><div className="section-top"><div><div className="eyebrow">03 / speed, with a denominator</div><h2>Measure the work you actually run.</h2></div><p>Recorded timings include the client and network. They are not a promise about every document, image or provider.</p></div><div className="method-grid"><article className="panel"><h3>One request, several questions</h3><p>Text inspection submits the atomic questions together. HTML can inspect several candidates; image analysis adds a separate vision stage. More content can mean more calls.</p></article><article className="panel"><h3>Reproduce the measurement</h3><pre className="code">pnpm record:jev</pre><p>Six synthetic evaluations: three content inspections and three intake triage cases. This is an explicit paid run. Keep returned model IDs, dates, failures and case labels alongside timings.</p></article></div></section></main></div>;
}
