import {afterEach,it,expect,vi} from 'vitest';
import {GET,POST} from '../app/api/scan/route';
const req=(body:unknown,origin='https://registry.example')=>new Request('https://registry.example/api/scan',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const configure=()=>{vi.stubEnv('NODE_ENV','development');vi.stubEnv('REGISTRY_ENABLE_URL_SCAN','1');vi.stubEnv('SCAN_WORKER_URL','http://127.0.0.1:9080/scan');vi.stubEnv('SCAN_WORKER_KEY','private-key');vi.stubEnv('DATABASE_URL','');vi.stubEnv('TURNSTILE_SECRET_KEY','');};
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
it('fails closed without production isolation endpoint, quota and challenge configuration',async()=>{vi.stubEnv('NODE_ENV','production');expect((await GET()).status).toBe(200);expect((await (await GET()).json()).enabled).toBe(false);expect((await POST(req({url:'https://example.com',semantic:false}))).status).toBe(503);});
it('rejects cross-origin, private and credential-bearing inputs before dispatch',async()=>{configure();const f=vi.fn();vi.stubGlobal('fetch',f);expect((await POST(req({url:'https://example.com',semantic:false},'https://other.example'))).status).toBe(403);for(const url of ['https://127.0.0.1','https://example.com/?secret=x','http://example.com'])expect((await POST(req({url,semantic:false}))).status).toBe(400);expect(f).not.toHaveBeenCalled();});
it('never fetches the user URL from Next and strips raw worker evidence',async()=>{configure();const fetcher=vi.fn(async(_url:unknown,_options:unknown)=>Response.json({action:'allow',risk:0,findings:[],findingCount:0,mode:'static',models:[],calls:0,inspectionMs:3,fetchMs:10,totalMs:13,bytes:200,redirects:0,coverage:'Initial HTML',detectorVersion:'0.1',scannedAt:new Date().toISOString(),html:'SECRET_RAW_HTML'}));vi.stubGlobal('fetch',fetcher);const response=await POST(req({url:'https://example.com',semantic:false}));expect(response.status).toBe(200);expect(fetcher.mock.calls[0]?.[0]).toBe('http://127.0.0.1:9080/scan');expect(JSON.stringify(await response.json())).not.toContain('SECRET_RAW_HTML');});
it('does not silently downgrade semantic requests or report malformed results as success',async()=>{configure();expect((await POST(req({url:'https://example.com',semantic:true}))).status).toBe(503);vi.stubGlobal('fetch',vi.fn(async()=>Response.json({action:'allow'})));expect((await POST(req({url:'https://example.com',semantic:false}))).status).toBe(503);});
